spring.application.name=backend
server.port=5000

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/palacio_del_mar

# JWT Configuration
jwt.secret=palaciodelmarsecretkeyforjwttokengeneration2026_verylongkey
jwt.expiration=86400000
