spring.application.name=backend
server.port=${SERVER_PORT:5000}

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://${MONGO_HOST:mongo}:27017/palacio_db
spring.mongodb.uri=mongodb://${MONGO_HOST:mongo}:27017/palacio_db
spring.data.mongodb.auto-index-creation=false

# JWT Configuration
jwt.secret=${JWT_SECRET:1cebc720b94ea82fec10c9b23952448c3e90f4b38aa3ac92b03d24e79c8bd9ff}
jwt.expiration=86400000
